parameters:
    redis_servers:
      -
        host: 127.0.0.1
        port: 6379
        name: null
        password: null

    search_per_page: 20

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
