parameters:
    redis_servers:
      -
        host: 127.0.0.1
        port: 6379
        name: localhost redis
        password:

    search_per_page: 20
    search_auto_max_keys: 10000

    locale: en
    secret: CwraFfMpOh4e9z1z8yj6
