eugef_php_red_expert_server:
    type:     rest
    resource: Eugef\PhpRedExpert\ApiBundle\Controller\ServerController

eugef_php_red_expert_database:
    type:     rest
    resource: Eugef\PhpRedExpert\ApiBundle\Controller\DatabaseController

eugef_php_red_expert_keys:
    type:     rest
    resource: Eugef\PhpRedExpert\ApiBundle\Controller\KeysController
