parameters:
#    eugef_php_red_expert.example.class: Eugef\PhpRedExpertBundle\Example

services:
#    eugef_php_red_expert.example:
#        class: %eugef_php_red_expert.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
